#!/bin/bash
# Core expectation tests
#
#  Copyright (C) 2014 Mike Gewitz
#
#  This file is part of shspec.
#
#  shspec is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##


describe succeed
  it will succeed when command exits with status code 0
    expect _expect--succeed 0
      to succeed
  end

  it will fail when command exits with non-zero status code
    expect _expect--succeed 1
      to fail
  end
end


describe fail
  it will succeed when command exits with non-zero status code
    expect _expect--fail 1
      to succeed
  end

  it will fail when command exits with status code 0
    expect _expect--fail 0
      to fail
  end
end

