#!/bin/bash
# Core expectations
#
#  Copyright (C) 2014 Mike Gewitz
#
#  This file is part of shspec.
#
#  shspec is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

[ -z $__INC_EXPECT_CORE ] || return
__INC_EXPECT_CORE=1


_expect--succeed() { test "$1" -eq 0; }
_expect--fail()    { test "$1" -ne 0; }

_expect--output()
{
  local -r cmp="$2"
  shift 2
  local -r clause="$*"

  local nl=
  if [ -n "$clause" ]; then
    [ "$clause" == 'without newline' ] \
      && nl=-n \
      || _bail "unrecognized output clause: $clause"
  fi

  # we will eventually be interested in this output
  diff <( echo $nl "$cmp" ) - &>/dev/null
}

